version: '3.8'

services:
  db:
    image: postgres
    container_name: medical_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: medical
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: medical_api
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123
      DATABASE_NAME: medical
